# Generated by Django 4.2.9 on 2024-10-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoshow',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='AutoShow/e9a98744-fc4e-4ddf-a203-c37c8e620d56%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='car',
            name='Views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='Image',
            field=models.FileField(upload_to='Cars/3e4c2c81-d746-483f-98ec-ca8c9e0f3c5e%Y%m%d'),
        ),
    ]
