# Generated by Django 4.2.9 on 2024-10-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='usersProfile/d6f2f14b-4341-48c3-b6ac-11a1f28b3e03%Y%m%d'),
        ),
    ]
